
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C2S_common.h"
namespace S2C2S {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_RequestLogin,
               
		Rmi_NotifyLoginSuccess,
               
		Rmi_NotifyLoginFailed,
               
		Rmi_JoinGameRoom,
               
		Rmi_Room_Appear,
               
		Rmi_Room_Disappear,
	};

	int g_RmiIDListCount = 6;

}


